### ISSUE TITLE
Problem with brightness

### ISSUE THREAD

**Issue by Tin123** [rricharz/pi-top-install#13]
First of all thanks for the scripts,
great work!
But it seems that brightness isn't working on my pi-top.

![2017-04-09-111802_1366x732_scrot](https://cloud.githubusercontent.com/assets/27134211/24836267/bcee4fa6-1d17-11e7-99ff-5e286b971dbc.png)

no matter what brightness setting i'm typing in, it always defaults to 5, nothing changes.
I've already disconnected the hub-controller from battery (for 5 min lol) but with no success.

Raspbian updated to latest, SPI enabled, followed your instructions (twice!),
don't know what to do so maybe you can shine some light on it =)

Thanks!

**Comment by rricharz** [comment]
Yes, the hub-controller does not seem to accept the command.  Do you think that brightness is indeed 5, which would be rather low? Have you used spi for something else on your pi-top?  Is there something else hooked up which might respond? Have you carefully checked the 40 pin cable? Are you using a fresh Raspbian?

**Comment by Tin123** [comment]
Don't know if it's really 5, but it's neither full bright nor lowest, like "in the middle".
Haven't used spi for something else and only the pi-top parts are hooked up.
Also i've checked it with 2 fresh Raspbian installs, doesn't work.
Already exchanged the Pi, disassabled the pi-top parts and put it back together...
the 40pin cable seems okay. 
your battery-script is working flawlessly, 
but maybe there's really a problem with the pins...
the shutdown-script is also not working.
Don't know how to check each pin to tell if the cable's really working correctly...

i've flashed the PitopOS just to check if the Brightness-Settings are working in there, 
but it doesn't...
Seems like the 40pin cable is not working properly.

Looking for a solution the check the cable and keep you up to date if you wish so :)

**Comment by rricharz** [comment]
If the receive pin MISO shorted to ground or open, I would expect that "receiving" is either 0x00 or 0xFF, if the send pin MOSI is open, I would just expect what you see, because the hub would always see a 0xFF command, which means report your settings, but don't change anything.  If you have an ohmmeter, you could check pins 19 (MOSI),21(MISO),23(CLOCK),24 and 26. If you have a pi-top-PROTO board, this would be fairly easy to do while power is off. Also, if you have 6 jumper cables and the PROTO board, you could just connect these pins and ground between the PROTO and the rpi, while the 40 pin cable is removed.

The fact that brightness does not work with pi-topOS means it is a hardware problem, which could involve the rpi, 40 pin cable or hub-controller. Most people who have such a problem have a bent or broken pin in the cable or the connectors. The fact that we receive something (the 0xAC) means that the spi connection is not completely broken. The fact that the battery display works, means that the cable is not connected the wrong way around.

If nothing helps, I would try to do the following: try with another rpi or ask pi-top for a new hub-controller and cable.

**Comment by Tin123** [comment]
Hi, thank you very much for your help!
I've connected it with the jumper cables to the PROTO but the problem remains, also exchanged the RPi, with no success..
The pins on the Rpi and the Hub are okay, nothing bend or broken.
Can't look inside the 40Pin Cable but the fact that it also doesn't work with jumper cables let me assume that the hub have to be broken.
Very strange, can't see anything unusual...

Well, i try to ask the Pi-Top team if they can help me out of this misery.

Again,
Thank you very much!
